# Generated by Django 3.1.1 on 2021-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cnpj", models.CharField(max_length=18)),
            ],
        ),
    ]
