# Generated by Django 3.1.1 on 2021-03-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="cnpj",
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
