# Generated by Django 3.1.1 on 2021-03-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('companies', '0002_auto_20210312_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
